apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: 581452407825.dkr.ecr.ap-south-1.amazonaws.com/docker-msb:ver2
        imagePullPolicy: Always
        name: k8s-ct
        ports:
        - containerPort: 3083
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  ports:
  - port: 80
    targetPort: 3083
  selector:
    app: webapp
