apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: 581452407825.dkr.ecr.ap-south-1.amazonaws.com/docker-msb:ver1
        imagePullPolicy: Always
        name: k8s-ct
        ports:
        - containerPort: 8080
        imagePullSecrets:
        - name: docker-hub
