apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: rakshithcg/rakshithg:latest
        imagePullPolicy: Always
        name: k8s-crt
        ports:
        - containerPort: 8085
